### ISSUE TITLE
purchase on website does not work

### ISSUE THREAD

**Issue by mooodin** [dcarrith/mpdtunes#10]
hi
unfortunately the purchase for the pro version of mpdtunes does not work
cheers
martin

**Comment by dcarrith** [comment]
@mooodin - I haven't been maintaining that site because I haven't had time.  I also haven't had time to keep this Github project current.  But, I'll be trying to push all the changes I have locally soon.  I've upgraded support for Laravel 5.1.x and have other changes too.  You're welcome to clone the project and try to get it working.  But, honestly, you might want to wait until I create a docker container or two sometime in the future.
