### ISSUE TITLE
Composer.json laravel 4 components not supported in laravel 5

### ISSUE THREAD

**Issue by Gergar** [dcarrith/mpdtunes#9]
Hello,

I am trying to do a fresh install on mpdtunes but i found references to libraries that are not supported in new laravel...

Can you let me know which references are really required so i can look if this can be fixed? Else we wont be able to installing under laravel 5 :(

Thanks!

**Comment by dcarrith** [comment]
@Gergar - I haven't been keeping this project up-to-date in Github.  I have actually already ported the project to Laravel 5.1.x locally.  However, I don't know when I'll have time to get all the changes pushed to Github.  It's been about 10 months since you opened this issue, so you've probably moved on anyway.
